name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: ls -al

  failed_job:
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Job fallido
        run: echo "Este trabajo ha fallado"

  second_jobs:
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "Hola mundo 2"
    
  working_with_variables:
    runs-on: ubuntu-latest

    steps:
        - name: Working dir
          id: step_variables
          run: echo "my_var=Hola mundo" >> $GITHUB_OUTPUT
        
        - name: Obtener mensaje
          run: echo "${{ steps.step_variables.outputs.my_var }}"

  generate_artifact:
    runs-on: ubuntu-latest

    steps:
        - name: Generar Archivo
          run: | 
            echo "Este es un archivo de prueba" > test.log

        - name: Subir el archivo como artefacto
          uses: actions/upload-artifact@v4
          with:
            name: archivo-test
            path: test.log